# src/AppBundle/Resources/config/serialization.yml
AppBundle\Entity\Auteur:
  attributes:
    id:
      groups : ['auteurs', 'livres']
    nom :
      groups : ['auteurs', 'livres']
    prenom:
      groups : ['auteurs', 'livres']
    livres :
      groups : ['auteurs']

AppBundle\Entity\Livre:
  attributes:
    id:
      groups : ['auteurs', 'livres','categories']
    titre :
      groups : ['auteurs', 'livres','categories']
    date_parution:
      groups : ['auteurs', 'livres','categories']
    date_ajout :
      groups : ['auteurs', 'livres','categories']
    photo :
      groups : ['auteurs', 'livres','categories']
    categorie: 
      groups : ['auteurs', 'livres']
    auteur :
      groups : ['livres','categories']
    commentaires :
      groups :  ['auteurs', 'livres','categories']

AppBundle\Entity\Categorie:
  attributes:
    id:
      groups: ['categories']
    genrePrincipal:
      groups: ['categories']
    sousGenre:
      groups: ['categories']
    livres:
      groups: ['categories']